# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestmodely:
  def __init__(self,driver):
    self.driver=driver
  def test_testmodelY(self):
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#dx-nav-item--vehicles > .tds-site-nav-item-text").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#dx-nav-item--vehicles > .tds-site-nav-item-text")))
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".active .dx-mega-menu-product:nth-child(2) .tds-link:nth-child(1)")))
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".active .dx-mega-menu-product:nth-child(2) .tds-link:nth-child(1)").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".tcl-hero__content-end")))
    Url=self.driver.current_url
    assert "https://www.tesla.com/tr_tr/modely"==Url   #Url ile sayfa doğrulama
    time.sleep(1)
